version: "3.9"

services:
  load_balancer:
    build: ./load_balancer
    image: load_balancer_image
    container_name: load_balancer_container
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      - net1

  shard_manager:
    build: ./shard_manager
    image: shard_manager_image
    container_name: shard_manager_container
    ports:
      - "5001:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      - net1
  map_db:
    image: mysql:8.0.36-debian
    container_name: map_db
    ports:
      - ":3306"
      - ":33060"
    environment:
      MYSQL_ROOT_PASSWORD: abc
      MYSQL_DATABASE: map_db
    networks:
      - net1

networks:
  net1:
